---

- name: Install docker
  hosts: localhost
  become: true
  vars_files:
    - "variables.yml"
  tasks:

    - name: Uninstall old versions
      yum:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Set up docker repository
      shell: |
        yum install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo

    - name: Install the latest version of Docker Engine and containerd
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Add the current user to the docker group
      user:
        name: "{{item}}"
        groups: docker
        append: yes
      loop:
        - "{{user}}"
        - jenkins

    - name: refresh user docker group membership
      command: newgrp docker

    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
