---

- name: Install docker
  hosts: localhost
  become: true
  vars_files:
    - "variables.yml"
  tasks:

    - name: Uninstall old versions
      yum:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
          - docker-compose
        state: absent

    - name: Set up docker repository
      shell: |
        yum install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install the latest version of Docker Engine and containerd
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      notify: Start and enable docker

    - name: Add the current user to the docker group
      user:
        name: "{{user}}"
        groups: docker
        append: yes

  handlers:
    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
