---
- hosts: localhost
  become: yes
  vars_files:
    - "variables.yml"
  tasks:
    - name: Install fontconfig (needed for jenkins in rhel9)
      dnf:
        name: "fontconfig"
        state: latest

    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install jenkins
      dnf:
        name: "jenkins-{{jenkins_version}}"
        state: latest

    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
        - '/var/lib/jenkins/plugins'

    - name: template the jenkins.yaml file
      template:
        src: "files/jcasc/jenkins.yaml.j2"
        dest: "/var/lib/jenkins/jenkins.yaml"

    - name: Copy the init files
      copy:
        src: "init.groovy.d/"
        dest: "/var/lib/jenkins/init.groovy.d/"

    - name: Set java_home in systemd/jenkins
      lineinfile:
        dest: /usr/lib/systemd/system/jenkins.service
        insertbefore: '\[Install\]'
        line: "{{ item }}"
      loop:
        - "Environment=\"JAVA_HOME=/usr/lib/java_{{java_version}}\""
        - 'Environment="JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins""'
        - 'Environment="CASC_JENKINS_CONFIG=/var/lib/jenkins/jenkins.yaml"'
        - 'Environment="JENKINS_OPTS="-Djava.awt.headless=true  -Djenkins.install.runSetupWizard=false -Djava.io.tmpdir=/var/cache/jenkins/tmp/""'

    - name: Set jenkins user to sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"

    - name: download jenkins-plugin-manager jar
      get_url:
        url: "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/{{plugin_manager_version}}/jenkins-plugin-manager-{{plugin_manager_version}}.jar"
        dest: /tmp/jenkins-plugin-manager.jar

    - name: Install plugins
      # The need to use the JAVA_HOME is linked to the bug that sudo java -version gives 1.8 not 11 installed her
      command:
        "/usr/lib/java_{{java_version}}/bin/java -jar /tmp/jenkins-plugin-manager.jar \
          --war /usr/share/java/jenkins.war \
          --plugin-download-directory /var/lib/jenkins/plugins \ 
          --plugin-file files/jcasc/plugins.txt"

    - name: update JENKINS_HOME ownership
      become: yes
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        state: directory
        recurse: yes

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        enabled: true
        state: restarted
