---
- hosts: localhost
  become: yes
  vars_files:
    - "variables.yml"
  tasks:
    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install jenkins
      dnf:
        name: "jenkins-{{jenkins_version}}"
        state: latest

    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
        - '/var/lib/jenkins/plugins'

    - name: Copy the jenkins.yaml file
      become: yes
      copy:
        src: "files/jcasc/jenkins.yaml"
        dest: "/var/lib/jenkins/jenkins.yaml"

    - name: Copy the init files
      become: yes
      copy:
        src: "init.groovy.d/"
        dest: "/var/lib/jenkins/init.groovy.d/"

    - name: Set java_home in systemd/jenkins
      lineinfile:
        dest: /usr/lib/systemd/system/jenkins.service
        insertbefore: '\[Install\]'
        line: "{{ item }}"
      loop:
        - "Environment=\"JAVA_HOME=/usr/lib/java_{{java_version}}\""
        - 'Environment="JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins""'
        - 'Environment="CASC_JENKINS_CONFIG=/var/lib/jenkins/jenkins.yaml"'
        - 'Environment="JENKINS_OPTS="-Djava.awt.headless=true  -Djenkins.install.runSetupWizard=false -Djava.io.tmpdir=/var/cache/jenkins/tmp/""'

    - name: download jenkins-cli jar
      get_url:
        url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
        dest: /tmp/jenkins-cli.jar

    - name: Set jenkins user to sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"

    - name: Install plugins
      command: "java -jar /tmp/jenkins-cli.jar -s http://localhost:8080 -auth admin:admin install-plugin configuration-as-code"
      become: no

    - name: update JENKINS_HOME ownership
      become: yes
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        state: directory
        recurse: yes

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        enabled: true
        state: restart
