---
- hosts: localhost
  become: yes
  vars_files:
    - "variables.yml"
  tasks:
    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: Install jenkins
      yum:
        name: jenkins
        state: latest

    - name: Set java_home in systemd/jenkins
      lineinfile:
        dest: /usr/lib/systemd/system/jenkins.service
        insertbefore: '\[Install\]'
        line: "{{ item }}"
      loop:
        - "Environment=\"JAVA_HOME=/usr/lib/java_{{java_version}}\""
        -
    - name: Set jenkins user to sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        enabled: true
        state: started
