---
- hosts: localhost
  become: yes
  vars_files:
    - "variables.yml"
  tasks:
    - name: jenkins yum repository
      become: yes
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: Install jenkins
      yum:
        name: "jenkins-{{jenkins_version}}"
        state: latest

    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
        - '/var/lib/jenkins/plugins'

    - name: Update JENKINS_JAVA_OPTIONS
      lineinfile:
        path: "/usr/lib/systemd/system/jenkins.service"
        regexp: ".*-Djava.awt.headless=true.*"
        line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djenkins.install.runSetupWizard=false -Djava.io.tmpdir=/var/cache/jenkins/tmp/ "'
        state: present

    - name: Update JENKINS_ARGS
      become: yes
      lineinfile:
        path: "/usr/lib/systemd/system/jenkins.service"
        regexp: ".*JENKINS_ARGS=.*"
        line: 'JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins"'
        state: present

    - name: download jenkins-plugin-manager
      get_url:
        url: "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/{{plugin_manager_version}}/jenkins-plugin-manager-{{plugin_manager_version}}.jar"
        dest: /tmp/jenkins-plugin-manager.jar

    - name: Copy the jenkins.yaml file
      become: yes
      copy:
        src: "files/jcasc/jenkins.yaml"
        dest: "/var/lib/jenkins/jenkins.yaml"

    - name: Copy the init files
      become: yes
      copy:
        src: "init.groovy.d/"
        dest: "/var/lib/jenkins/init.groovy.d/"

    - name: run the jenkins-plugin-manager
      become: yes
      command: "java -jar /tmp/jenkins-plugin-manager.jar --jenkins-version jenkins-{{jenkins_version}}  --plugin-file files/jcasc/plugins.yaml --plugin-download-directory /var/lib/jenkins/plugins"

    - name: update JENKINS_HOME ownership
      become: yes
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        state: directory
        recurse: yes

    - name: Set java_home in systemd/jenkins
      lineinfile:
        dest: /usr/lib/systemd/system/jenkins.service
        insertbefore: '\[Install\]'
        line: "{{ item }}"
      loop:
        - "Environment=\"JAVA_HOME=/usr/lib/java_{{java_version}}\""

    - name: Set jenkins user to sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        enabled: true
        state: started
