---

- name: Install controller host tools
  hosts: localhost
  become: yes

- name: Include tools_playbook
  import_playbook: tools_playbook.yml

- name: Include jenkins_playbook
  import_playbook: jenkins_playbook.yml

- name: Include tools_playbook
  import_playbook: docker_playbook.yml


