---

- name: Install controller host tools
  hosts: localhost
  become: yes

- name: Install  Tools
  import_playbook: tools_playbook.yml

- name: Install Jenkins
  import_playbook: jenkins_playbook.yml

- name: Install  Artifactory
  import_playbook: artifactory_playbook.yml

- name: Install Docker
  import_playbook: docker_playbook.yml




