
---
- hosts: localhost
  become: yes

  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-1.8.0-openjdk-devel
      state: present

  - name: Install git
    yum:
      name: git
      state: latest

  - name: Install maven
    yum:
      name: git
      state: latest
https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip