---
- hosts: localhost
  become: yes
  vars_files:
    - "variables.yml"
  tasks:

    - name: Check the maven directory exists
      stat:
        path: "/usr/lib/java_{{java_version}}"
      register: java_dir


    - name: Download java
      get_url:
        url: "https://builds.openlogic.com/downloadJDK/openlogic-openjdk/{{java_version}}/openlogic-openjdk-{{java_version}}-linux-x64.tar.gz"
        dest: /tmp/
      when: not java_dir.stat.exists

    - name: Extract java tar
      unarchive:
        src: "/tmp/openlogic-openjdk-{{java_version}}-linux-x64.tar.gz"
        dest: /usr/lib/
      when: not java_dir.stat.exists

    - name: rename java folder
      command: "mv /usr/lib/openlogic-openjdk-{{java_version}}-linux-x64.tar.gz /usr/lib/java_{{java_version}}"
      when: not java_dir.stat.exists

    - name: Check the maven directory exists
      stat:
        path: /opt/maven
      register: maven_dir

    - name: Download maven
      get_url:
        url: "https://mirrors.estointernet.in/apache/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz"
        dest: /tmp/
      when: not maven_dir.stat.exists

    - name: Extract MAVEN tar
      unarchive:
        src: "/tmp/apache-maven-{{maven_version}}-bin.tar.gz"
        dest: /opt
      when: not maven_dir.stat.exists

    - name: rename maven folder
      command: "mv /opt/apache-maven-{{maven_version}} /opt/maven"
      when: not maven_dir.stat.exists

    - name: Set maven env variables
      lineinfile:
        dest: /etc/bashrc
        line: "{{ item }}"
      loop:
        - export JAVA_HOME=/usr/lib/java_{{java_version}}
        - export M2_HOME=/opt/maven
        - export M2=$M2_HOME/bin
        - export PATH=$JAVA_HOME:$M2:$PATH

    - name: apply env variables
      command: "source /etc/bashrc"
