---
- hosts: localhost
  become: yes
  vars_files:
    - "variables.yml"
  tasks:
    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: Install java
      yum:
        name: "java-{{java_version}}-openjdk"
        state: present

    - name: Check the maven directory exists
      stat:
        path: /opt/maven
      register: maven_dir

    - name: Download maven
      get_url:
        url: "https://mirrors.estointernet.in/apache/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz"
        dest: /tmp/
      when: not maven_dir.stat.exists

    - name: Extract MAVEN tar
      unarchive:
        src: "/tmp/apache-maven-{{maven_version}}-bin.tar.gz"
        dest: /opt
      when: not maven_dir.stat.exists

    - name: rename maven folder
      command: "mv /opt/apache-maven-{{maven_version}} /opt/maven"
      when: not maven_dir.stat.exists

    - name: Set maven env variables
      lineinfile:
        dest: /etc/bashrc
        line: "{{ item }}"
      loop:
        - export M2_HOME=/opt/maven
        - export M2=$M2_HOME/bin
        - export PATH=$M2:$PATH

    - name: apply env variables
      command: "source /etc/bashrc"
